# _______       _____             _____              _____ 
# ___    |___  ___  /_______________  /______ _________  /_
# __  /| |  / / /  __/  __ \_  ___/  __/  __ `/_  ___/  __/
# _  ___ / /_/ // /_ / /_/ /(__  )/ /_ / /_/ /_  /   / /_  
# /_/  |_\__,_/ \__/ \____//____/ \__/ \__,_/ /_/    \__/  
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1        # You Must Have A Polkit
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH
exec-once = dbus-update-activation-environment --systemd --all # For XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # For XDPH
#exec-once = swww init # Wallpaper Daemon
exec-once = hyprpaper 
exec-once = swaync # Notification Center
exec-once = hyprpicker --daemon # Color Picker Daemon
exec-once = cliphist --daemon # Clipboard History Daemon

exec-once = waybar 
exec-once = wl-clipboard-history -t # Clipboard
exec-once = dolphin --daemon # File Managers Daemon
exec-once = $HOME/.config/hypr/hyprdesktop # Ensure Proper Portals Are Loaded
exec-once = hyprctl setcursor Bibata-Modern-Ice 32 # Set Proper Curser & Size
